
import { jsPDF } from "jspdf";
import fs from "fs";
import path from "path";

const generatePdf = () => {
    const doc = new jsPDF();
    const lineHeight = 6;
    let y = 20;

    // --- Helpers ---
    const addWrappedText = (text: string, fontSize: number, fontType: string, color: [number, number, number], indent: number = 14) => {
        doc.setFontSize(fontSize);
        doc.setFont("helvetica", fontType);
        doc.setTextColor(...color);
        const splitText = doc.splitTextToSize(text, 180 - (indent - 14));
        doc.text(splitText, indent, y);
        y += (splitText.length * lineHeight) + 2;
    };

    const checkPageBreak = (neededSpace: number) => {
        if (y + neededSpace > 280) {
            doc.addPage();
            y = 20;
        }
    };

    const addSection = (title: string) => {
        checkPageBreak(30);
        y += 5;
        // Section Header Background
        doc.setFillColor(240, 253, 244); // Light green bg
        doc.rect(14, y - 6, 182, 14, "F");

        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(22, 163, 74); // Green 600
        doc.text(title, 16, y + 4);
        y += 14;
    };

    const addSubsection = (title: string) => {
        checkPageBreak(20);
        y += 2;
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(0, 0, 0); // Black
        doc.text(title, 14, y);
        y += 6;
    };

    const addListItem = (title: string, description: string) => {
        checkPageBreak(25);
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(40, 40, 40);
        doc.text(`• ${title}:`, 18, y);

        const titleWidth = doc.getTextWidth(`• ${title}:`);

        doc.setFontSize(11);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(80, 80, 80);

        // Split description to fit
        const splitDesc = doc.splitTextToSize(description, 180 - 18);
        // If first line fits on same line as title, do it, else new line (simplified: just new line for consistency or complex logic)
        // Let's do next line for clean look usually, or append. 
        // Let's append if simple.
        doc.text(splitDesc, 18, y + 6);
        y += (splitDesc.length * lineHeight) + 8;
    };

    // --- Content ---

    // Title Page
    doc.setFontSize(26);
    doc.setTextColor(22, 163, 74);
    doc.setFont("helvetica", "bold");
    doc.text("Technical Architecture Document", 105, 100, { align: "center" });

    doc.setFontSize(16);
    doc.setTextColor(100);
    doc.text("Scrap Marketplace Platform", 105, 110, { align: "center" });

    doc.setFontSize(12);
    doc.text("Generated by Antigravity", 105, 120, { align: "center" });
    doc.text(new Date().toLocaleDateString(), 105, 126, { align: "center" });

    doc.addPage();
    y = 20;

    // 1. Executive Summary
    addSection("1. Executive Summary");
    addWrappedText(
        "The Scrap Marketplace Platform is a modern web application designed to connect customers with scrap agents/collectors. It facilitates scheduling pickups, managing rates, and processing transactions efficiently. The system is built on a scalable, type-safe stack using Next.js and MongoDB.",
        11, "normal", [60, 60, 60]
    );

    // 2. System Overview
    addSection("2. System Modules");
    addSubsection("Customer Portal");
    addWrappedText("Allows users to book pickups, view scrap rates, track request status, and manage their profile and address book.", 11, "normal", [80, 80, 80], 18);

    addSubsection("Agent App");
    addWrappedText("Provides agents with a dashboard to view assigned pickups, navigate to locations, and process collections with invoice generation.", 11, "normal", [80, 80, 80], 18);

    addSubsection("Admin Dashboard");
    addWrappedText("Centralized control for managing users, agents, rates, and viewing system-wide analytics and reports.", 11, "normal", [80, 80, 80], 18);

    // 3. Frontend Architecture
    addSection("3. Frontend Architecture");
    addWrappedText("The frontend utilizes the Next.js App Router for a hybrid rendering approach (Server Components + Client Components), ensuring optimal performance and SEO.", 11, "normal", [60, 60, 60]);

    addSubsection("Core Framework");
    addListItem("Next.js 16 (App Router)", "Handles routing, bundling, and rendering. Uses Server Components by default for data fetching efficiency.");
    addListItem("React 19", "Latest React version supporting Actions and experimental hooks for cleaner async logic.");
    addListItem("TypeScript", "Strict type-checking enabled to prevent runtime errors and improve developer velocity.");

    addSubsection("UI & Styling");
    addListItem("Tailwind CSS v4", "High-performance utility-first CSS engine. Configured with a custom design system token set.");
    addListItem("Radix UI", "Headless, accessible UI primitives used for complex interactive elements (Modals, Dropdowns, Tabs).");
    addListItem("Framer Motion", "Declarative animation library used for page transitions and micro-interactions.");
    addListItem("Lucide React", "Consistent, lightweight SVG icon set.");

    addSubsection("State Management");
    addListItem("Zustand", "Lightweight store for global client-side state (e.g., active session details, cart/booking drafts).");

    addSubsection("Specialized Features");
    addListItem("Maps (Leaflet & Google)", "Interactive maps for address selection (Leaflet + OpenStreetMap) and geocoding services.");
    addListItem("React Hook Form + Zod", "Robust form handling with schema-based validation for all user inputs.");
    addListItem("Recharts", "Composable charting library used in the Admin Analytics dashboard.");

    // 4. Backend Architecture
    addSection("4. Backend Architecture");
    addWrappedText("The backend logic is integrated directly into the Next.js application via Server Actions, eliminating the need for a separate API server for most operations.", 11, "normal", [60, 60, 60]);

    addSubsection("Server Layer");
    addListItem("Server Actions", "Async functions that execute on the server, callable directly from UI components. Handles DB mutations securely.");
    addListItem("Node.js Runtime", "Executes the server environment code.");

    addSubsection("Data Persistence");
    addListItem("MongoDB Atlas", "Document-oriented NoSQL database. Chosen for its schema flexibility tailored to evolving product requirements.");
    addListItem("Prisma ORM", "Type-safe database client. Provides auto-generated types matching the schema.prisma definition.");

    addSubsection("Utilities");
    addListItem("jsPDF & autoTable", "Client-side generation of PDF invoices and reports for bookings.");
    addListItem("Sonner", "Toaster notification system for user feedback.");

    // Footer on last page
    y = 280;
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(150, 150, 150);
    doc.text("Confidential - Internal Use Only", 14, y);

    // Save
    const outputPath = path.resolve("public", "TechnicalArchitecture.pdf");
    const pdfOutput = doc.output("arraybuffer");
    fs.writeFileSync(outputPath, Buffer.from(pdfOutput));

    console.log(`PDF generated successfully at: ${outputPath}`);
};

generatePdf();
